### PR TITLE
Management command

### PR DESCRIPTION
**Pull request by sudoer-zero**
I added a management command for cleaning expired files via CLI. #42

### CODE REVIEW

**Review by TobySuch — CHANGES_REQUESTED** [review]
Hi @sudoer-zero 
Thanks for the work on this! I just have a couple of comments:
1. I'm having some issues running the tests on my local machine - related to the colours. Not sure why the automated tests are passing, I'm guessing they suppress the colours some how.

If we change `test_commands.py` Line 35 to `*args + ("--no-color",),`, it will mean it should run on any machine happily. It is either that or we change the tests to be `assertIn` rather than `assertEqual`.

2. This is really nitpicky, but I'm not a fan of having to type an underscore in a command name, any chance you could rename the command to `cleanupexpired.py` to avoid that?

Other than that, awesome work! Will merge it in once thats resolved. Thanks

**Comment by TobySuch** [comment]
Also this PR contributes towards #43, not #42

**Comment by sudoer-zero** [comment]
> Also this PR contributes towards #43, not #42

Sorry for the mistake, Now it's fixed.

**Review by TobySuch — APPROVED** [review]
Looks good! Some small things we can for QOL such as a count of how many files are removed but we can do that at a later date. Will merge in now.

**Pull request merged**
